// Host simulation harness for the Cybrid firmware.
//
// Builds one sketch (SKETCH, passed by run.sh) against sim_arduino.h, plays a fixed set of scripted
// hammer motions on every key, and prints every MIDI event to stdout. run.sh builds several
// firmware versions and compares their outputs. The harness itself fails (exit 1) on:
//   - two Teensy outputs fighting on a (shorted) cable line, or two note boards on the bus at once
//   - a key that does not produce exactly one note-on per stroke in the velocity sweep
//   - velocities outside 1-127, or velocity increasing with flight time
#include "sim_arduino.h"

#include <algorithm>
#include <utility>

namespace sim {
uint64_t nowUs = 0;
int pinMode_[64];
int pinLevel[64];
long lineFights = 0;
long busFights = 0;
std::vector<MidiEvent> events;

static std::vector<std::pair<uint64_t, Zone>> timeline[128];
static size_t cursor[128];

Zone zoneOf(int note) {
  auto &tl = timeline[note];
  size_t &i = cursor[note];
  while (i + 1 < tl.size() && tl[i + 1].first <= nowUs) i++;
  return (tl.empty() || tl[i].first > nowUs) ? REST : tl[i].second;
}
} // namespace sim

UsbMidi usbMIDI;
SerialStub Serial;

#include "protos.h" // generated by run.sh: prototypes of the sketch's functions
#include SKETCH

using namespace sim;

static const int FIRST_NOTE = 21;
static const int LAST_NOTE = 20 + SIM_PIANO_KEYS;
static const uint64_t LOOP_US = 9; // measured full-scan period of the real instrument
static const uint64_t HOLD_US = 40; // how long the hammer stays within the strike point

static void at(int note, uint64_t t, Zone z) { timeline[note].push_back({t, z}); }

// One ordinary stroke: rise through the damper point, fly from escapement to strike in
// flightUs, rebound, and fall back to rest when the key is released.
static uint64_t stroke(int note, uint64_t t, uint64_t flightUs) {
  at(note, t, DAMPER);
  at(note, t += 300, ESCAP);
  at(note, t += flightUs, STRIKE);
  at(note, t += HOLD_US, ESCAP);
  at(note, t += 200, DAMPER);
  at(note, t += 1500, REST);
  return t;
}

int main() {
  const uint64_t sweep[] = {150, 200, 250, 300, 400, 600, 1000, 2000, 4000, 8000, 13000};
  const int nSweep = sizeof(sweep) / sizeof(sweep[0]);
  uint64_t t = 1000, sweepStart[16], sweepEnd[16];

  // 1. Velocity sweep: every key struck together with the same flight time.
  for (int s = 0; s < nSweep; s++) {
    sweepStart[s] = t;
    uint64_t end = t;
    for (int n = FIRST_NOTE; n <= LAST_NOTE; n++) end = std::max(end, stroke(n, t, sweep[s]));
    sweepEnd[s] = end;
    t = end + 3000;
  }

  // 2. Staggered chord: different start times and flight times on every key.
  {
    uint64_t end = t;
    for (int n = FIRST_NOTE; n <= LAST_NOTE; n++) {
      int k = n - FIRST_NOTE;
      end = std::max(end, stroke(n, t + 13 * k, 150 + 97 * ((k * 7) % 60)));
    }
    t = end + 3000;
  }

  // 3. Repetition with the key held (hammer falls to the damper zone only), 4. an aborted
  // slow press followed by a real stroke, 5. escapement-zone rebound without a re-strike,
  // 6. a creeping press slower than the velocity table.
  for (int n = FIRST_NOTE; n <= LAST_NOTE; n++) {
    uint64_t u = t;
    at(n, u, DAMPER); at(n, u += 300, ESCAP); at(n, u += 400, STRIKE); at(n, u += HOLD_US, ESCAP);
    at(n, u += 200, DAMPER); at(n, u += 3000, ESCAP); at(n, u += 800, STRIKE); at(n, u += HOLD_US, ESCAP);
    at(n, u += 200, DAMPER); at(n, u += 1500, REST);
    u += 3000;
    at(n, u, DAMPER); at(n, u += 300, ESCAP); at(n, u += 1000, DAMPER); at(n, u += 2000, ESCAP);
    at(n, u += 600, STRIKE); at(n, u += HOLD_US, ESCAP); at(n, u += 200, DAMPER); at(n, u += 1500, REST);
    u += 3000;
    at(n, u, DAMPER); at(n, u += 300, ESCAP); at(n, u += 500, STRIKE); at(n, u += HOLD_US, ESCAP);
    at(n, u += 300, STRIKE); at(n, u += HOLD_US, ESCAP); at(n, u += 200, DAMPER); at(n, u += 1500, REST);
    u += 3000;
    u = stroke(n, u, 20000);
    if (n == LAST_NOTE) t = u + 3000;
  }

  setup();
  while (nowUs < t) { loop(); nowUs += LOOP_US; }

  int failures = 0;
  if (lineFights || busFights) {
    fprintf(stderr, "FAIL: %ld cable-line fights, %ld bus fights\n", lineFights, busFights);
    failures++;
  }
  for (int n = FIRST_NOTE; n <= LAST_NOTE; n++) {
    int prev = 128;
    for (int s = 0; s < nSweep; s++) {
      int ons = 0, vel = 0;
      for (auto &e : events)
        if (e.type == 0 && e.a == n && e.b > 0 && e.t >= sweepStart[s] && e.t <= sweepEnd[s]) { ons++; vel = e.b; }
      if (ons != 1 || vel < 1 || vel > 127 || vel > prev) {
        fprintf(stderr, "FAIL: note %d, flight %llu us: %d note-on(s), velocity %d (previous %d)\n",
                n, (unsigned long long)sweep[s], ons, vel, prev);
        failures++;
      }
      prev = vel;
    }
  }

  for (auto &e : events) printf("%llu %s %d %d\n", (unsigned long long)e.t, e.type ? "cc" : "note", e.a, e.b);
  fprintf(stderr, "%zu MIDI events, %d failure(s)\n", events.size(), failures);
  return failures ? 1 : 0;
}
